name: micromag-euler-dipole
channels:
  - conda-forge
  - defaults
dependencies:
  - python==3.10.*
  - numpy
  - scipy
  - matplotlib
  - pandas
  - scikit-image
  - xarray
  - netcdf4
  - jupyterlab
  - black
  # For stereonets
  - mplstereonet
  # Fatiando
  - pooch
  - verde
  - harmonica
  - choclo
  - pip:
    - git+https://github.com/fatiando/harmonica
